#!/usr/bin/env python3
"""
trace_spine - one game's trace, as a page's spine in `engineering-practices.md`
§7's structure, or as the `--dump-events` text.

    python plans/trace_spine.py TRACE.jsonl [--out PAGE.html] [--title T]
                                [--from SEQ] [--to SEQ] [--batch N] [--branch B]
    python plans/trace_spine.py TRACE.jsonl --events        # the --dump-events format

The trace is what the engine's five emit points wrote (`mtgsim/src/state/
trace.rs`): one JSON object per line. The page is `plans/traces/viewer.html`
with the selected records embedded and the pin filled in - the same viewer
that reads a file dropped on it, so there is one renderer and this script
only selects and pins. What comes out is the SPINE: the step rows, one per
record, each labelled by what it consulted. The map's questions, the "where
the reads differ" table and the closing section stay authored, and the page
marks their places.

`--events` is decision 5 of row A4c made literal: the performed-event
stream goes to the sink, so `fuzz_games --dump-events` is one projection of a
trace - `event` records rendered the way `dump_event_log` renders the log.

Selection: `--from`/`--to` bound `seq`; `--batch N` keeps the records of one
top-level batch (its `batch` through its `batch_end`, nested batches and the
riders that follow included); `--branch B` keeps one fork's records plus the
root's up to the fork. The `game` and `object` records always ride along, so
a partial page still names its ids.
"""

import argparse
import datetime as dt
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TEMPLATE = os.path.join(HERE, "traces", "viewer.html")


def read(path):
    records = []
    with open(path, encoding="utf-8") as f:
        for n, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue
            try:
                records.append(json.loads(line))
            except json.JSONDecodeError as e:
                sys.exit(f"{path}:{n}: not JSON ({e})")
    return records


def select(records, args):
    keep = records
    if args.frm is not None:
        keep = [r for r in keep if r["seq"] >= args.frm]
    if args.to is not None:
        keep = [r for r in keep if r["seq"] <= args.to]
    if args.branch is not None:
        fork = next((r for r in records if r["kind"] == "fork" and r["to"] == args.branch), None)
        fork_at = fork["seq"] if fork else 0
        keep = [r for r in keep if r["branch"] == args.branch or (r["branch"] == 0 and r["seq"] <= fork_at)]
    if args.batch is not None:
        # From the top-level `batch` record with that id to the last record
        # before the next top-level batch begins - riders and nested batches
        # sit between the two.
        start = next((r["seq"] for r in keep if r["kind"] == "batch" and r["depth"] == 1 and r["batch"] == args.batch), None)
        if start is None:
            sys.exit(f"no top-level batch {args.batch}")
        end = next((r["seq"] for r in keep if r["kind"] == "batch" and r["depth"] == 1 and r["seq"] > start), None)
        keep = [r for r in keep if start <= r["seq"] and (end is None or r["seq"] < end)]
    always = [r for r in records if r["kind"] in ("game", "object")]
    seen = {r["seq"] for r in keep}
    return sorted(keep + [r for r in always if r["seq"] not in seen], key=lambda r: r["seq"])


def events_text(records):
    """`dump_event_log`'s per-line shape, from the `event` records."""
    return "\n".join(f"  {r['index']:>4}: {r['text']}" for r in records if r["kind"] == "event")


def page(records, args, source):
    with open(TEMPLATE, encoding="utf-8") as f:
        template = f.read()
    game = next((r for r in records if r["kind"] == "game"), {})
    title = args.title or f"Spine: {game.get('label', os.path.basename(source))}"
    pin = (
        f"  Generated by plans/trace_spine.py on {dt.date.today().isoformat()} from {os.path.basename(source)}\n"
        f"  ({len(records)} records). The engine that wrote it: commit {game.get('commit', 'unknown')}, "
        f"seed {game.get('seed', 'none')}, {game.get('players', '?')} players.\n"
        f"  A spine, not a page (engineering-practices.md section 7.1): the step rows are generated,\n"
        f"  the argument is not. Pinned like every trace page - never maintained."
    )
    # `</script>` cannot appear inside the embedded data; JSON allows the
    # escaped form, and the viewer's parser reads it back as the same text.
    body = "\n".join(json.dumps(r, separators=(",", ":"), ensure_ascii=False) for r in records)
    body = body.replace("</", "<\\/")
    out = template.replace("<!--__PIN__-->", f"<!--\n{pin}\n-->")
    out = out.replace("__TITLE__", html_escape(title))
    out = out.replace("/*__TRACE__*/", body)
    return out


def html_escape(s):
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("trace", help="a .jsonl the engine wrote")
    ap.add_argument("--out", help="the page to write (default: the trace's name with .html)")
    ap.add_argument("--title", help="the page's title (default: the trace's label)")
    ap.add_argument("--from", dest="frm", type=int, help="first seq to keep")
    ap.add_argument("--to", type=int, help="last seq to keep")
    ap.add_argument("--batch", type=int, help="keep one top-level batch, by its id")
    ap.add_argument("--branch", type=int, help="keep one fork's records, and the root's up to the fork")
    ap.add_argument("--events", action="store_true", help="print the --dump-events text instead of writing a page")
    args = ap.parse_args()

    records = select(read(args.trace), args)
    if args.events:
        print(events_text(records))
        return
    out = args.out or os.path.splitext(args.trace)[0] + ".html"
    with open(out, "w", encoding="utf-8") as f:
        f.write(page(records, args, args.trace))
    kinds = {}
    for r in records:
        kinds[r["kind"]] = kinds.get(r["kind"], 0) + 1
    print(f"{out}: {len(records)} records - " + ", ".join(f"{k} {n}" for k, n in sorted(kinds.items())))


if __name__ == "__main__":
    main()
