//! Type definitions for the continuous effects / layer system (CR 613).
//!
//! These types represent the core data structures for tracking and applying
//! continuous effects in layer order. The layer system computes effective
//! characteristics for all game objects by walking registered effects in
//! layer + timestamp order.

use std::collections::HashSet;

use crate::objects::card_data::AbilityDef;
use crate::types::card_types::{CardType, Subtype, Supertype};
use crate::types::colors::Color;
use crate::types::effects::{Duration, PermanentFilter};
use crate::types::ids::{AbilityId, ObjectId, PlayerId};
use crate::types::keywords::KeywordAbility;
use crate::types::mana::ManaCost;

/// Unique identifier for a registered continuous effect.
pub type EffectId = u64;

/// Timestamp for ordering effects within a layer (CR 613.7).
pub type Timestamp = u64;

/// CR 613 layers, including sublayers. The derived `Ord` gives correct
/// application order: effects are sorted by layer first, then by timestamp
/// within the same layer.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum Layer {
    /// Layer 1 — copy effects (CR 613.2). Face-down and copy.
    /// Stubbed for Phase LA; implemented in Phase LD.
    Layer1Copy,
    /// Layer 2 — control-changing effects (CR 613.3).
    Layer2Control,
    /// Layer 3 — text-changing effects. Deferred indefinitely (25 cards).
    Layer3Text,
    /// Layer 4 — type-changing effects (types, subtypes, supertypes).
    Layer4Type,
    /// Layer 5 — color-changing effects.
    Layer5Color,
    /// Layer 6 — ability-adding and ability-removing effects.
    Layer6Ability,
    /// Layer 7b — effects that set P/T to specific values (CR 613.4b).
    Layer7bSetPT,
    /// Layer 7c — P/T modifications: +N/+N pumps, anthems (CR 613.4c).
    /// Counters are also applied here but read directly from BattlefieldEntity,
    /// not stored as registered effects.
    Layer7cModifyPT,
    /// Layer 7d — switch P/T (CR 613.4d).
    Layer7dSwitchPT,
}

/// One side of a power/toughness modification.
///
/// Two variants rather than one, because the two carry different things and
/// neither subsumes the other:
///
/// - `Fixed` is a **signed** literal. `ModifyPowerToughness { power: -1, .. }`
///   is ordinary (Weakness, `-1/-1` counters), and `AmountExpr::Fixed` is `u64`,
///   so the amount language cannot express it.
/// - `Dynamic` is an expression evaluated during the layer walk, every time, on
///   the frame as of the end of the previous layer. March of the Machines' "each
///   equal to its mana value" and Tarmogoyf's graveyard count are both this: the
///   value has to track the game rather than be snapshotted at registration,
///   which is what CR 604.7 and 613.4a require.
#[derive(Debug, Clone, PartialEq)]
pub enum PtValue {
    Fixed(i32),
    Dynamic(crate::types::effects::AmountExpr),
}

/// What a continuous effect does to each affected object.
/// Each variant belongs to exactly one layer.
#[derive(Debug, Clone, PartialEq)]
pub enum EffectModification {
    // --- Layer 2 ---
    SetController(PlayerId),

    // --- Layer 4 ---
    AddType(CardType),
    RemoveType(CardType),
    SetTypes(HashSet<CardType>),
    AddSubtype(Subtype),
    RemoveSubtype(Subtype),
    SetSubtypes(HashSet<Subtype>),
    AddSupertype(Supertype),
    RemoveSupertype(Supertype),
    SetSupertypes(HashSet<Supertype>),

    // --- Layer 5 ---
    AddColor(Color),
    SetColors(HashSet<Color>),
    RemoveAllColors,

    // --- Layer 6 ---
    GrantKeyword(KeywordAbility),
    RemoveKeyword(KeywordAbility),
    LoseAllAbilities,

    // --- Layer 7b ---
    SetPowerToughness { power: PtValue, toughness: PtValue },

    // --- Layer 7c ---
    ModifyPowerToughness { power: PtValue, toughness: PtValue },

    // --- Layer 7d ---
    SwitchPowerToughness,
}

/// Where a continuous effect came from, which determines whether its
/// existence is conditional (CR 613.7a vs. 613.7b).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EffectOrigin {
    /// CR 613.7b — created by the resolution of a spell or ability. The effect
    /// exists unconditionally until its `Duration` ends; nothing can take away
    /// the ability that made it, because it was made by a one-shot resolution.
    Resolution,

    /// CR 613.7a — generated by a static ability of `source`. Existence is
    /// *conditional*: the effect only applies while `source` still has
    /// `ability`. CR 305.7 (Blood Moon) and Layer 6 ability removal can both
    /// take it away, so `compute.rs` re-checks this at every layer rather than
    /// trusting registry membership.
    ///
    /// `(source, ability)` is the identity pair — `AbilityId` names an ability
    /// *definition*, which two objects sharing an `Arc<CardData>` also share,
    /// so the object id is what makes it an ability *on an object*. Same
    /// pairing `mana_helpers::activatable_abilities` and
    /// `engine::mana::activate_mana_ability` already use.
    StaticAbility { ability: AbilityId },
}

/// Selects which objects a continuous effect applies to.
#[derive(Debug, Clone, PartialEq)]
pub enum AffectedSet {
    /// The source permanent itself ("this creature has flying").
    SourceOnly,
    /// A data-driven filter ("creatures you control").
    Filter {
        filter: PermanentFilter,
        controller: Option<PlayerId>,
    },
    /// A fixed set captured at effect creation time.
    /// Pump spells use this — the target is locked at resolution.
    Fixed(Vec<ObjectId>),
}

/// CR-level identity of a continuous effect, for CR 613.6.
///
/// The registry stores one `ContinuousEffect` row per `EffectModification`,
/// because each modification belongs to exactly one layer. But CR 613.6 talks
/// about *the effect* — "if an effect starts to apply in one layer, it will
/// continue to be applied to the same set of objects in each other applicable
/// layer". March of the Machines is one effect with a Layer 4 part and a Layer
/// 7b part; in the registry that is two rows with two `EffectId`s. Rows that
/// belong to the same CR-level effect share an `EffectGroup`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum EffectGroup {
    /// All rows generated by one static ability of one object. Keyed on the
    /// ability rather than the timestamp because `register_static_effects`
    /// allocates a separate timestamp per atom of a multi-atom ability.
    StaticAbility(ObjectId, AbilityId),
    /// All rows a single resolution registered together, which share a source
    /// and a timestamp (CR 613.7b).
    Resolution(ObjectId, Timestamp),
}

/// A single active continuous effect in the registry.
#[derive(Debug, Clone)]
pub struct ContinuousEffect {
    /// Unique ID for this effect instance.
    pub id: EffectId,
    /// The object that generates this effect.
    pub source: ObjectId,
    /// Whether this effect's existence is conditional on a static ability
    /// still being present (CR 613.7a) or unconditional (CR 613.7b).
    pub origin: EffectOrigin,
    /// Which layer this effect applies in.
    pub layer: Layer,
    /// When the effect becomes inactive (abstract — from card text).
    pub duration: Duration,
    /// The player who controlled the spell/ability that created this effect.
    /// Resolves "your" in durations like UntilYourNextTurn.
    pub controller: PlayerId,
    /// The turn number when this effect was created. Used with player-relative
    /// durations to prevent immediate expiry (e.g. "until your next turn"
    /// shouldn't expire on the same turn it was created).
    pub created_on_turn: u32,
    /// Timestamp for ordering within the same layer (CR 613.7).
    pub timestamp: Timestamp,
    /// Which objects this effect applies to.
    pub affected: AffectedSet,
    /// What the effect does to each affected object.
    pub modification: EffectModification,
}

impl ContinuousEffect {
    /// The CR-level effect this registry row belongs to. See `EffectGroup`.
    pub fn group(&self) -> EffectGroup {
        match self.origin {
            EffectOrigin::StaticAbility { ability } => {
                EffectGroup::StaticAbility(self.source, ability)
            }
            EffectOrigin::Resolution => EffectGroup::Resolution(self.source, self.timestamp),
        }
    }
}

/// The computed effective characteristics of a game object after all
/// continuous effects have been applied. This is the output of
/// `compute_characteristics`.
#[derive(Debug, Clone, PartialEq)]
pub struct EffectiveCharacteristics {
    pub name: String,
    pub mana_cost: Option<ManaCost>,
    pub colors: HashSet<Color>,
    pub types: HashSet<CardType>,
    pub subtypes: HashSet<Subtype>,
    pub supertypes: HashSet<Supertype>,
    pub keywords: HashSet<KeywordAbility>,
    pub abilities: Vec<AbilityDef>,
    pub power: Option<i32>,
    pub toughness: Option<i32>,
    pub controller: PlayerId,
}
