//! Storage for active continuous effects (CR 613).
//!
//! This is the data owner — lives on GameState. The computation logic
//! lives in `engine/layers/compute.rs`.

use crate::engine::layers::types::{ContinuousEffect, EffectId, Layer, Timestamp};
use crate::types::ids::ObjectId;

/// Cheap, registry-wide facts that let `compute_characteristics` skip work it
/// would otherwise have to do per object per layer.
///
/// `layers-architecture.md` §5.1 describes this struct with three more fields
/// (`touches_hidden_zones`, `touches_stack`, `has_active_cdas`) for the
/// hidden-zone fast path and CDA handling. Those land with the systems that
/// need them; the struct is introduced here with the one field that has a
/// caller, so the later work extends it rather than growing a parallel counter.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct RegistryScopeSummary {
    /// True iff some `EffectGroup` has more than one row in the registry.
    ///
    /// CR 613.6's "started applying" bookkeeping only changes an answer for a
    /// CR-level effect the registry split across several rows — a single-row
    /// group is marked as started immediately after its only row applies, and
    /// nothing ever reads the mark. When this is false, `compute.rs` skips the
    /// bookkeeping entirely rather than hashing an `EffectGroup` twice per
    /// effect per layer. Worth 3.3x on a static-heavy board; see the comment
    /// on the `started` set in `apply_effects`.
    pub any_multi_row_group: bool,
}

/// Owns all active continuous effects in the game.
#[derive(Debug, Clone)]
pub struct ContinuousEffectRegistry {
    effects: Vec<ContinuousEffect>,
    next_effect_id: EffectId,
    summary: RegistryScopeSummary,
}

impl ContinuousEffectRegistry {
    pub fn new() -> Self {
        ContinuousEffectRegistry {
            effects: Vec::new(),
            next_effect_id: 1,
            summary: RegistryScopeSummary::default(),
        }
    }

    /// Registry-wide summary flags. See `RegistryScopeSummary`.
    pub fn summary(&self) -> &RegistryScopeSummary {
        &self.summary
    }

    /// Recompute `summary` from scratch.
    ///
    /// A full walk on every mutation rather than incremental counters: adds and
    /// removes are rare next to reads, and a counter that drifts would show up
    /// as a silently skipped existence check — the exact class of bug this
    /// phase exists to remove.
    fn recompute_summary(&mut self) {
        let mut seen: std::collections::HashSet<crate::engine::layers::types::EffectGroup> =
            std::collections::HashSet::with_capacity(self.effects.len());
        self.summary.any_multi_row_group = self.effects.iter().any(|e| !seen.insert(e.group()));

        debug_assert!(self.is_sorted(), "registry order invariant violated after mutation");
    }

    /// Register a new continuous effect. Returns its unique ID.
    pub fn add(&mut self, mut effect: ContinuousEffect) -> EffectId {
        // CR 604.3a(3) — a CDA affects only the object that has it, so it needs
        // no `AffectedSet` and never becomes a registry row. `layers::cda`
        // applies them off the object's own ability list instead. Layer 7a is
        // the CDA-only sublayer, so a row landing here means someone routed a
        // CDA through registration; catch it at the door rather than letting it
        // apply twice.
        debug_assert!(
            effect.layer != Layer::Layer7aCdaPT,
            "Layer 7a is applied intrinsically, never from the registry \
             (CR 604.3a(3)); effect from source {:?} tried to register there",
            effect.source
        );

        let id = self.next_effect_id;
        self.next_effect_id += 1;
        effect.id = id;
        let key = (effect.layer, effect.timestamp, effect.id);
        let pos = self
            .effects
            .partition_point(|e| (e.layer, e.timestamp, e.id) < key);
        self.effects.insert(pos, effect);
        self.recompute_summary();
        id
    }

    /// Remove a specific effect by its ID. Returns the removed effect if found.
    pub fn remove(&mut self, id: EffectId) -> Option<ContinuousEffect> {
        if let Some(pos) = self.effects.iter().position(|e| e.id == id) {
            let removed = self.effects.remove(pos);
            self.recompute_summary();
            Some(removed)
        } else {
            None
        }
    }

    /// Remove all effects generated by a given source object.
    /// Used when a permanent leaves the battlefield.
    pub fn remove_by_source(&mut self, source: ObjectId) -> Vec<ContinuousEffect> {
        self.retain_effects(|e| e.source != source)
    }

    /// All effects in a layer, already in application order (CR 613.7).
    ///
    /// No sorting happens here. `effects` is *maintained* in
    /// `(layer, timestamp, id)` order by `add`, so a layer is a contiguous
    /// range and this is two binary searches and a slice.
    ///
    /// `EffectId` is the sub-order within a timestamp, and it is doing real
    /// work rather than breaking an accidental tie: CR 613.7a gives every
    /// continuous effect from a static ability of one object *the object's*
    /// timestamp, so all of an object's static-ability effects share one by
    /// design. Ids are assigned in registration order and never reused, which
    /// is what 613.7a's "the relative order of those timestamps remains the
    /// same" asks for.
    ///
    /// Removals preserve order for the same reason — see `retain_effects`.
    ///
    /// (Not yet CR 613.8: dependency ordering is unimplemented, so this is
    /// timestamp order only. See Deferred Migrations item 8.)
    pub fn effects_in_layer(&self, layer: Layer) -> &[ContinuousEffect] {
        debug_assert!(self.is_sorted(), "registry order invariant violated");
        let lo = self.effects.partition_point(|e| e.layer < layer);
        let hi = self.effects.partition_point(|e| e.layer <= layer);
        &self.effects[lo..hi]
    }

    /// The `(layer, timestamp, id)` ordering invariant `effects_in_layer`
    /// depends on. Checked under `debug_assertions` on every read and after
    /// every mutation, so a future code path that pushes without maintaining
    /// order fails a test rather than silently misordering a layer.
    fn is_sorted(&self) -> bool {
        self.effects
            .windows(2)
            .all(|w| (w[0].layer, w[0].timestamp, w[0].id) < (w[1].layer, w[1].timestamp, w[1].id))
    }

    /// Remove every effect failing `keep`, returning them; order preserved.
    ///
    /// One pass. The obvious `while i < len { if .. { v.remove(i) } }` is
    /// `O(n²)`, since each `Vec::remove` shifts the tail — and `swap_remove`,
    /// which is what this used before the registry became ordered, is not an
    /// option any more because it destroys the invariant above.
    fn retain_effects(&mut self, keep: impl Fn(&ContinuousEffect) -> bool) -> Vec<ContinuousEffect> {
        let mut removed = Vec::new();
        let mut kept = Vec::with_capacity(self.effects.len());
        for effect in self.effects.drain(..) {
            if keep(&effect) {
                kept.push(effect);
            } else {
                removed.push(effect);
            }
        }
        self.effects = kept;
        self.recompute_summary();
        removed
    }

    /// Iterate over all registered effects.
    pub fn iter(&self) -> impl Iterator<Item = &ContinuousEffect> {
        self.effects.iter()
    }

    /// Returns true if no effects are registered.
    pub fn is_empty(&self) -> bool {
        self.effects.is_empty()
    }

    /// Number of registered effects.
    pub fn len(&self) -> usize {
        self.effects.len()
    }

    /// Remove effects that expire during the cleanup step (rule 514.2).
    ///
    /// Handles:
    /// - `UntilEndOfTurn` — always expires at cleanup.
    /// - `UntilEndOfYourNextTurn` (future) — expires at cleanup if the active
    ///   player matches the effect's controller AND the current turn is after
    ///   the turn the effect was created on.
    pub fn remove_expired_at_cleanup(
        &mut self,
        active_player: crate::types::ids::PlayerId,
        current_turn: u32,
    ) -> Vec<ContinuousEffect> {
        use crate::types::effects::Duration;
        // Suppress unused variable warnings until multi-turn durations are added
        // (UntilEndOfYourNextTurn would read both).
        let _ = (active_player, current_turn);
        self.retain_effects(|e| !matches!(e.duration, Duration::UntilEndOfTurn))
    }

    /// Remove effects that expire at the start of a player's turn.
    ///
    /// Handles:
    /// - `UntilYourNextTurn` — expires at the beginning of the controller's
    ///   next turn (checked at untap step). Only fires if the current turn is
    ///   strictly after the turn the effect was created on (prevents immediate
    ///   expiry when created on your own turn).
    pub fn remove_expired_at_turn_start(
        &mut self,
        active_player: crate::types::ids::PlayerId,
        current_turn: u32,
    ) -> Vec<ContinuousEffect> {
        use crate::types::effects::Duration;
        self.retain_effects(|e| {
            !matches!(e.duration, Duration::UntilYourNextTurn)
                || e.controller != active_player
                || current_turn <= e.created_on_turn
        })
    }

    /// Allocate the next timestamp value.
    pub fn next_timestamp(counter: &mut Timestamp) -> Timestamp {
        let ts = *counter;
        *counter += 1;
        ts
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::engine::layers::types::*;
    use crate::types::effects::Duration;
    use uuid::Uuid;

    fn make_effect(source: ObjectId, layer: Layer, timestamp: Timestamp) -> ContinuousEffect {
        ContinuousEffect {
            id: 0, // will be assigned by registry
            source,
            origin: EffectOrigin::Resolution,
            layer,
            duration: Duration::UntilEndOfTurn,
            controller: 0,
            created_on_turn: 1,
            timestamp,
            affected: AffectedSet::SourceOnly,
            modification: EffectModification::ModifyPowerToughness { power: PtValue::Fixed(1), toughness: PtValue::Fixed(1) },
        }
    }

    #[test]
    fn test_add_and_iter() {
        let mut reg = ContinuousEffectRegistry::new();
        let src = Uuid::new_v4();
        let id = reg.add(make_effect(src, Layer::Layer7cModifyPT, 1));
        assert_eq!(id, 1);
        assert_eq!(reg.len(), 1);
        assert_eq!(reg.iter().next().unwrap().id, 1);
        assert_eq!(reg.next_effect_id, 2);
    }

    #[test]
    fn test_remove_by_id() {
        let mut reg = ContinuousEffectRegistry::new();
        let src = Uuid::new_v4();
        let id1 = reg.add(make_effect(src, Layer::Layer7cModifyPT, 1));
        let _id2 = reg.add(make_effect(src, Layer::Layer7cModifyPT, 2));
        assert_eq!(reg.len(), 2);

        let removed = reg.remove(id1);
        assert!(removed.is_some());
        assert_eq!(reg.len(), 1);
    }

    #[test]
    fn test_remove_by_source() {
        let mut reg = ContinuousEffectRegistry::new();
        let src_a = Uuid::new_v4();
        let src_b = Uuid::new_v4();
        reg.add(make_effect(src_a, Layer::Layer7cModifyPT, 1));
        reg.add(make_effect(src_a, Layer::Layer6Ability, 2));
        reg.add(make_effect(src_b, Layer::Layer7cModifyPT, 3));

        let removed = reg.remove_by_source(src_a);
        assert_eq!(removed.len(), 2);
        assert_eq!(reg.len(), 1);
        assert_eq!(reg.iter().next().unwrap().source, src_b);
    }

    // COVERS-PARTIAL: ATOM-613.7-001
    #[test]
    fn test_effects_in_layer_sorted_by_timestamp() {
        let mut reg = ContinuousEffectRegistry::new();
        let src = Uuid::new_v4();
        reg.add(make_effect(src, Layer::Layer7cModifyPT, 5));
        reg.add(make_effect(src, Layer::Layer7cModifyPT, 2));
        reg.add(make_effect(src, Layer::Layer6Ability, 3));
        reg.add(make_effect(src, Layer::Layer7cModifyPT, 8));

        let layer7c = reg.effects_in_layer(Layer::Layer7cModifyPT);
        assert_eq!(layer7c.len(), 3);
        assert_eq!(layer7c[0].timestamp, 2);
        assert_eq!(layer7c[1].timestamp, 5);
        assert_eq!(layer7c[2].timestamp, 8);
    }

    #[test]
    fn test_is_empty() {
        let mut reg = ContinuousEffectRegistry::new();
        assert!(reg.is_empty());
        let src = Uuid::new_v4();
        reg.add(make_effect(src, Layer::Layer7cModifyPT, 1));
        assert!(!reg.is_empty());
    }

    // COVERS-PARTIAL: ATOM-611.2a-001
    #[test]
    fn test_remove_expired_at_cleanup_removes_until_end_of_turn() {
        let mut reg = ContinuousEffectRegistry::new();
        let src = Uuid::new_v4();
        // UntilEndOfTurn effect
        reg.add(make_effect(src, Layer::Layer7cModifyPT, 1));
        // WhileSourceOnBattlefield effect (should NOT be removed)
        let mut permanent_effect = make_effect(src, Layer::Layer7cModifyPT, 2);
        permanent_effect.duration = Duration::WhileSourceOnBattlefield;
        reg.add(permanent_effect);

        assert_eq!(reg.len(), 2);
        let removed = reg.remove_expired_at_cleanup(0, 1);
        assert_eq!(removed.len(), 1);
        assert_eq!(reg.len(), 1);
        assert_eq!(reg.iter().next().unwrap().duration, Duration::WhileSourceOnBattlefield);
    }

    #[test]
    fn test_remove_expired_at_turn_start_until_your_next_turn() {
        let mut reg = ContinuousEffectRegistry::new();
        let src = Uuid::new_v4();

        // Effect created by player 0 on turn 1, duration UntilYourNextTurn
        let mut effect = make_effect(src, Layer::Layer7cModifyPT, 1);
        effect.duration = Duration::UntilYourNextTurn;
        effect.controller = 0;
        effect.created_on_turn = 1;
        reg.add(effect);

        // Turn 1, player 0's turn — should NOT expire (same turn it was created)
        let removed = reg.remove_expired_at_turn_start(0, 1);
        assert_eq!(removed.len(), 0);
        assert_eq!(reg.len(), 1);

        // Turn 2, player 1's turn — should NOT expire (wrong player)
        let removed = reg.remove_expired_at_turn_start(1, 2);
        assert_eq!(removed.len(), 0);
        assert_eq!(reg.len(), 1);

        // Turn 3, player 0's next turn — SHOULD expire
        let removed = reg.remove_expired_at_turn_start(0, 3);
        assert_eq!(removed.len(), 1);
        assert_eq!(reg.len(), 0);
    }

    #[test]
    fn test_until_your_next_turn_expires_on_extra_turn() {
        // Extra turns advance turn_number, so an extra turn for the controller
        // IS their "next turn" and the effect correctly expires at its start.
        let mut reg = ContinuousEffectRegistry::new();
        let src = Uuid::new_v4();

        let mut effect = make_effect(src, Layer::Layer7cModifyPT, 1);
        effect.duration = Duration::UntilYourNextTurn;
        effect.controller = 0;
        effect.created_on_turn = 1;
        reg.add(effect);

        // Turn 2 is an extra turn for player 0 — effect expires (turn 2 > 1)
        let removed = reg.remove_expired_at_turn_start(0, 2);
        assert_eq!(removed.len(), 1);
    }
}
