//! Storage for active continuous effects (CR 613).
//!
//! This is the data owner — lives on GameState. The computation logic
//! lives in `engine/layers/compute.rs`.

use crate::engine::layers::types::{ContinuousEffect, EffectId, Layer, Timestamp};
use crate::types::ids::ObjectId;

/// Cheap, registry-wide facts that let `compute_characteristics` skip work it
/// would otherwise have to do per object per layer.
///
/// `layers-architecture.md` §5.1 describes this struct with three more fields
/// (`touches_hidden_zones`, `touches_stack`, `has_active_cdas`) for the
/// hidden-zone fast path and CDA handling. Those land with the systems that
/// need them; the struct is introduced here with the one field that has a
/// caller, so the later work extends it rather than growing a parallel counter.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct RegistryScopeSummary {
    /// True iff some active effect could change which abilities an object has.
    ///
    /// When false, every object's effective abilities equal its printed ones,
    /// so no static ability can have gone missing and the CR 613.7a existence
    /// re-check in `compute.rs` is skipped entirely. This is the common case.
    pub any_ability_changing: bool,
}

/// Owns all active continuous effects in the game.
#[derive(Debug, Clone)]
pub struct ContinuousEffectRegistry {
    effects: Vec<ContinuousEffect>,
    next_effect_id: EffectId,
    summary: RegistryScopeSummary,
}

impl ContinuousEffectRegistry {
    pub fn new() -> Self {
        ContinuousEffectRegistry {
            effects: Vec::new(),
            next_effect_id: 1,
            summary: RegistryScopeSummary::default(),
        }
    }

    /// Registry-wide summary flags. See `RegistryScopeSummary`.
    pub fn summary(&self) -> &RegistryScopeSummary {
        &self.summary
    }

    /// Recompute `summary` from scratch.
    ///
    /// A full walk on every mutation rather than incremental counters: adds and
    /// removes are rare next to reads, and a counter that drifts would show up
    /// as a silently skipped existence check — the exact class of bug this
    /// phase exists to remove.
    fn recompute_summary(&mut self) {
        self.summary.any_ability_changing = self
            .effects
            .iter()
            .any(|e| e.modification.can_change_abilities());
    }

    /// Register a new continuous effect. Returns its unique ID.
    pub fn add(&mut self, mut effect: ContinuousEffect) -> EffectId {
        let id = self.next_effect_id;
        self.next_effect_id += 1;
        effect.id = id;
        self.effects.push(effect);
        self.recompute_summary();
        id
    }

    /// Remove a specific effect by its ID. Returns the removed effect if found.
    pub fn remove(&mut self, id: EffectId) -> Option<ContinuousEffect> {
        if let Some(pos) = self.effects.iter().position(|e| e.id == id) {
            let removed = self.effects.swap_remove(pos);
            self.recompute_summary();
            Some(removed)
        } else {
            None
        }
    }

    /// Remove all effects generated by a given source object.
    /// Used when a permanent leaves the battlefield.
    pub fn remove_by_source(&mut self, source: ObjectId) -> Vec<ContinuousEffect> {
        let mut removed = Vec::new();
        let mut i = 0;
        while i < self.effects.len() {
            if self.effects[i].source == source {
                removed.push(self.effects.swap_remove(i));
            } else {
                i += 1;
            }
        }
        self.recompute_summary();
        removed
    }

    /// Get all effects in a given layer, sorted by timestamp.
    pub fn effects_in_layer(&self, layer: Layer) -> Vec<&ContinuousEffect> {
        let mut result: Vec<&ContinuousEffect> = self.effects
            .iter()
            .filter(|e| e.layer == layer)
            .collect();
        result.sort_by_key(|e| e.timestamp);
        result
    }

    /// Iterate over all registered effects.
    pub fn iter(&self) -> impl Iterator<Item = &ContinuousEffect> {
        self.effects.iter()
    }

    /// Returns true if no effects are registered.
    pub fn is_empty(&self) -> bool {
        self.effects.is_empty()
    }

    /// Number of registered effects.
    pub fn len(&self) -> usize {
        self.effects.len()
    }

    /// Remove effects that expire during the cleanup step (rule 514.2).
    ///
    /// Handles:
    /// - `UntilEndOfTurn` — always expires at cleanup.
    /// - `UntilEndOfYourNextTurn` (future) — expires at cleanup if the active
    ///   player matches the effect's controller AND the current turn is after
    ///   the turn the effect was created on.
    pub fn remove_expired_at_cleanup(
        &mut self,
        active_player: crate::types::ids::PlayerId,
        current_turn: u32,
    ) -> Vec<ContinuousEffect> {
        use crate::types::effects::Duration;
        let mut removed = Vec::new();
        let mut i = 0;
        while i < self.effects.len() {
            let should_expire = match self.effects[i].duration {
                Duration::UntilEndOfTurn => true,
                // Future: UntilEndOfYourNextTurn would check:
                // self.effects[i].controller == active_player
                //     && current_turn > self.effects[i].created_on_turn
                _ => false,
            };
            if should_expire {
                removed.push(self.effects.swap_remove(i));
            } else {
                i += 1;
            }
        }
        // Suppress unused variable warnings until multi-turn durations are added
        let _ = (active_player, current_turn);
        self.recompute_summary();
        removed
    }

    /// Remove effects that expire at the start of a player's turn.
    ///
    /// Handles:
    /// - `UntilYourNextTurn` — expires at the beginning of the controller's
    ///   next turn (checked at untap step). Only fires if the current turn is
    ///   strictly after the turn the effect was created on (prevents immediate
    ///   expiry when created on your own turn).
    pub fn remove_expired_at_turn_start(
        &mut self,
        active_player: crate::types::ids::PlayerId,
        current_turn: u32,
    ) -> Vec<ContinuousEffect> {
        use crate::types::effects::Duration;
        let mut removed = Vec::new();
        let mut i = 0;
        while i < self.effects.len() {
            let should_expire = match self.effects[i].duration {
                Duration::UntilYourNextTurn => {
                    self.effects[i].controller == active_player
                        && current_turn > self.effects[i].created_on_turn
                }
                _ => false,
            };
            if should_expire {
                removed.push(self.effects.swap_remove(i));
            } else {
                i += 1;
            }
        }
        self.recompute_summary();
        removed
    }

    /// Allocate the next timestamp value.
    pub fn next_timestamp(counter: &mut Timestamp) -> Timestamp {
        let ts = *counter;
        *counter += 1;
        ts
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::engine::layers::types::*;
    use crate::types::effects::Duration;
    use uuid::Uuid;

    fn make_effect(source: ObjectId, layer: Layer, timestamp: Timestamp) -> ContinuousEffect {
        ContinuousEffect {
            id: 0, // will be assigned by registry
            source,
            origin: EffectOrigin::Resolution,
            layer,
            duration: Duration::UntilEndOfTurn,
            controller: 0,
            created_on_turn: 1,
            timestamp,
            affected: AffectedSet::SourceOnly,
            modification: EffectModification::ModifyPowerToughness { power: 1, toughness: 1 },
        }
    }

    #[test]
    fn test_add_and_iter() {
        let mut reg = ContinuousEffectRegistry::new();
        let src = Uuid::new_v4();
        let id = reg.add(make_effect(src, Layer::Layer7cModifyPT, 1));
        assert_eq!(id, 1);
        assert_eq!(reg.len(), 1);
        assert_eq!(reg.iter().next().unwrap().id, 1);
        assert_eq!(reg.next_effect_id, 2);
    }

    #[test]
    fn test_remove_by_id() {
        let mut reg = ContinuousEffectRegistry::new();
        let src = Uuid::new_v4();
        let id1 = reg.add(make_effect(src, Layer::Layer7cModifyPT, 1));
        let _id2 = reg.add(make_effect(src, Layer::Layer7cModifyPT, 2));
        assert_eq!(reg.len(), 2);

        let removed = reg.remove(id1);
        assert!(removed.is_some());
        assert_eq!(reg.len(), 1);
    }

    #[test]
    fn test_remove_by_source() {
        let mut reg = ContinuousEffectRegistry::new();
        let src_a = Uuid::new_v4();
        let src_b = Uuid::new_v4();
        reg.add(make_effect(src_a, Layer::Layer7cModifyPT, 1));
        reg.add(make_effect(src_a, Layer::Layer6Ability, 2));
        reg.add(make_effect(src_b, Layer::Layer7cModifyPT, 3));

        let removed = reg.remove_by_source(src_a);
        assert_eq!(removed.len(), 2);
        assert_eq!(reg.len(), 1);
        assert_eq!(reg.iter().next().unwrap().source, src_b);
    }

    // COVERS-PARTIAL: ATOM-613.7-001
    #[test]
    fn test_effects_in_layer_sorted_by_timestamp() {
        let mut reg = ContinuousEffectRegistry::new();
        let src = Uuid::new_v4();
        reg.add(make_effect(src, Layer::Layer7cModifyPT, 5));
        reg.add(make_effect(src, Layer::Layer7cModifyPT, 2));
        reg.add(make_effect(src, Layer::Layer6Ability, 3));
        reg.add(make_effect(src, Layer::Layer7cModifyPT, 8));

        let layer7c = reg.effects_in_layer(Layer::Layer7cModifyPT);
        assert_eq!(layer7c.len(), 3);
        assert_eq!(layer7c[0].timestamp, 2);
        assert_eq!(layer7c[1].timestamp, 5);
        assert_eq!(layer7c[2].timestamp, 8);
    }

    #[test]
    fn test_is_empty() {
        let mut reg = ContinuousEffectRegistry::new();
        assert!(reg.is_empty());
        let src = Uuid::new_v4();
        reg.add(make_effect(src, Layer::Layer7cModifyPT, 1));
        assert!(!reg.is_empty());
    }

    // COVERS-PARTIAL: ATOM-611.2a-001
    #[test]
    fn test_remove_expired_at_cleanup_removes_until_end_of_turn() {
        let mut reg = ContinuousEffectRegistry::new();
        let src = Uuid::new_v4();
        // UntilEndOfTurn effect
        reg.add(make_effect(src, Layer::Layer7cModifyPT, 1));
        // WhileSourceOnBattlefield effect (should NOT be removed)
        let mut permanent_effect = make_effect(src, Layer::Layer7cModifyPT, 2);
        permanent_effect.duration = Duration::WhileSourceOnBattlefield;
        reg.add(permanent_effect);

        assert_eq!(reg.len(), 2);
        let removed = reg.remove_expired_at_cleanup(0, 1);
        assert_eq!(removed.len(), 1);
        assert_eq!(reg.len(), 1);
        assert_eq!(reg.iter().next().unwrap().duration, Duration::WhileSourceOnBattlefield);
    }

    #[test]
    fn test_remove_expired_at_turn_start_until_your_next_turn() {
        let mut reg = ContinuousEffectRegistry::new();
        let src = Uuid::new_v4();

        // Effect created by player 0 on turn 1, duration UntilYourNextTurn
        let mut effect = make_effect(src, Layer::Layer7cModifyPT, 1);
        effect.duration = Duration::UntilYourNextTurn;
        effect.controller = 0;
        effect.created_on_turn = 1;
        reg.add(effect);

        // Turn 1, player 0's turn — should NOT expire (same turn it was created)
        let removed = reg.remove_expired_at_turn_start(0, 1);
        assert_eq!(removed.len(), 0);
        assert_eq!(reg.len(), 1);

        // Turn 2, player 1's turn — should NOT expire (wrong player)
        let removed = reg.remove_expired_at_turn_start(1, 2);
        assert_eq!(removed.len(), 0);
        assert_eq!(reg.len(), 1);

        // Turn 3, player 0's next turn — SHOULD expire
        let removed = reg.remove_expired_at_turn_start(0, 3);
        assert_eq!(removed.len(), 1);
        assert_eq!(reg.len(), 0);
    }

    #[test]
    fn test_until_your_next_turn_expires_on_extra_turn() {
        // Extra turns advance turn_number, so an extra turn for the controller
        // IS their "next turn" and the effect correctly expires at its start.
        let mut reg = ContinuousEffectRegistry::new();
        let src = Uuid::new_v4();

        let mut effect = make_effect(src, Layer::Layer7cModifyPT, 1);
        effect.duration = Duration::UntilYourNextTurn;
        effect.controller = 0;
        effect.created_on_turn = 1;
        reg.add(effect);

        // Turn 2 is an extra turn for player 0 — effect expires (turn 2 > 1)
        let removed = reg.remove_expired_at_turn_start(0, 2);
        assert_eq!(removed.len(), 1);
    }
}
