//! Storage for active continuous effects (CR 613).
//!
//! This is the data owner — lives on GameState. The computation logic
//! lives in `engine/layers/compute.rs`.

use crate::engine::layers::types::{ContinuousEffect, EffectId, Layer, Timestamp};
use crate::types::ids::ObjectId;

/// Owns all active continuous effects in the game.
#[derive(Debug, Clone)]
pub struct ContinuousEffectRegistry {
    effects: Vec<ContinuousEffect>,
    next_effect_id: EffectId,
}

impl ContinuousEffectRegistry {
    pub fn new() -> Self {
        ContinuousEffectRegistry {
            effects: Vec::new(),
            next_effect_id: 1,
        }
    }

    /// Register a new continuous effect. Returns its unique ID.
    pub fn add(&mut self, mut effect: ContinuousEffect) -> EffectId {
        let id = self.next_effect_id;
        self.next_effect_id += 1;
        effect.id = id;
        self.effects.push(effect);
        id
    }

    /// Remove a specific effect by its ID. Returns the removed effect if found.
    pub fn remove(&mut self, id: EffectId) -> Option<ContinuousEffect> {
        if let Some(pos) = self.effects.iter().position(|e| e.id == id) {
            Some(self.effects.swap_remove(pos))
        } else {
            None
        }
    }

    /// Remove all effects generated by a given source object.
    /// Used when a permanent leaves the battlefield.
    pub fn remove_by_source(&mut self, source: ObjectId) -> Vec<ContinuousEffect> {
        let mut removed = Vec::new();
        let mut i = 0;
        while i < self.effects.len() {
            if self.effects[i].source == source {
                removed.push(self.effects.swap_remove(i));
            } else {
                i += 1;
            }
        }
        removed
    }

    /// Get all effects in a given layer, sorted by timestamp.
    pub fn effects_in_layer(&self, layer: Layer) -> Vec<&ContinuousEffect> {
        let mut result: Vec<&ContinuousEffect> = self.effects
            .iter()
            .filter(|e| e.layer == layer)
            .collect();
        result.sort_by_key(|e| e.timestamp);
        result
    }

    /// Iterate over all registered effects.
    pub fn iter(&self) -> impl Iterator<Item = &ContinuousEffect> {
        self.effects.iter()
    }

    /// Returns true if no effects are registered.
    pub fn is_empty(&self) -> bool {
        self.effects.is_empty()
    }

    /// Number of registered effects.
    pub fn len(&self) -> usize {
        self.effects.len()
    }

    /// Allocate the next timestamp value.
    pub fn next_timestamp(counter: &mut Timestamp) -> Timestamp {
        let ts = *counter;
        *counter += 1;
        ts
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::engine::layers::types::*;
    use crate::types::effects::Duration;
    use uuid::Uuid;

    fn make_effect(source: ObjectId, layer: Layer, timestamp: Timestamp) -> ContinuousEffect {
        ContinuousEffect {
            id: 0, // will be assigned by registry
            source,
            layer,
            duration: Duration::UntilEndOfTurn,
            timestamp,
            affected: AffectedSet::SourceOnly,
            modification: EffectModification::ModifyPowerToughness { power: 1, toughness: 1 },
        }
    }

    #[test]
    fn test_add_and_iter() {
        let mut reg = ContinuousEffectRegistry::new();
        let src = Uuid::new_v4();
        let id = reg.add(make_effect(src, Layer::Layer7cModifyPT, 1));
        assert_eq!(id, 1);
        assert_eq!(reg.len(), 1);
        assert_eq!(reg.iter().next().unwrap().id, 1);
        assert_eq!(reg.next_effect_id, 2);
    }

    #[test]
    fn test_remove_by_id() {
        let mut reg = ContinuousEffectRegistry::new();
        let src = Uuid::new_v4();
        let id1 = reg.add(make_effect(src, Layer::Layer7cModifyPT, 1));
        let _id2 = reg.add(make_effect(src, Layer::Layer7cModifyPT, 2));
        assert_eq!(reg.len(), 2);

        let removed = reg.remove(id1);
        assert!(removed.is_some());
        assert_eq!(reg.len(), 1);
    }

    #[test]
    fn test_remove_by_source() {
        let mut reg = ContinuousEffectRegistry::new();
        let src_a = Uuid::new_v4();
        let src_b = Uuid::new_v4();
        reg.add(make_effect(src_a, Layer::Layer7cModifyPT, 1));
        reg.add(make_effect(src_a, Layer::Layer6Ability, 2));
        reg.add(make_effect(src_b, Layer::Layer7cModifyPT, 3));

        let removed = reg.remove_by_source(src_a);
        assert_eq!(removed.len(), 2);
        assert_eq!(reg.len(), 1);
        assert_eq!(reg.iter().next().unwrap().source, src_b);
    }

    #[test]
    fn test_effects_in_layer_sorted_by_timestamp() {
        let mut reg = ContinuousEffectRegistry::new();
        let src = Uuid::new_v4();
        reg.add(make_effect(src, Layer::Layer7cModifyPT, 5));
        reg.add(make_effect(src, Layer::Layer7cModifyPT, 2));
        reg.add(make_effect(src, Layer::Layer6Ability, 3));
        reg.add(make_effect(src, Layer::Layer7cModifyPT, 8));

        let layer7c = reg.effects_in_layer(Layer::Layer7cModifyPT);
        assert_eq!(layer7c.len(), 3);
        assert_eq!(layer7c[0].timestamp, 2);
        assert_eq!(layer7c[1].timestamp, 5);
        assert_eq!(layer7c[2].timestamp, 8);
    }

    #[test]
    fn test_is_empty() {
        let mut reg = ContinuousEffectRegistry::new();
        assert!(reg.is_empty());
        let src = Uuid::new_v4();
        reg.add(make_effect(src, Layer::Layer7cModifyPT, 1));
        assert!(!reg.is_empty());
    }
}
